import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{createClient}from"@supabase/supabase-js";
import{jsPDF}from"jspdf";
import{PieChart,Pie,Cell,ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid}from"recharts";
import"./style.css";

const url=import.meta.env.VITE_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const sb=url&&key?createClient(url,key):null;
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n)||0);
const dateNow=()=>new Date().toISOString().slice(0,10);

function Brand({compact=false}){return <div className={compact?"brand compact":"brand"}><div className="brandMark">NP</div><div><strong>NP INTERIOR DESIGN</strong>{!compact&&<small>DESIGN YOUR TOMORROW</small>}</div></div>}

function Login(){
 const[e,se]=useState("");const[p,sp]=useState("");const[m,sm]=useState("");const[busy,sbsy]=useState(false);
 if(!sb)return <div className="login"><div className="loginCard"><Brand/><h2>Payment Manager</h2><p className="muted">Supabase configuration is missing.</p><p className="error">Create the .env file and add your publishable key.</p></div></div>;
 return <div className="login"><form className="loginCard" onSubmit={async x=>{x.preventDefault();sm("");sbsy(true);const{error}=await sb.auth.signInWithPassword({email:e.trim(),password:p});sm(error?.message||"");sbsy(false)}}><Brand/><div className="loginTitle"><span>SECURE ACCESS</span><h2>Payment Manager</h2><p>Manage projects, collections and payment history.</p></div><label>Email<input type="email" placeholder="Enter email" value={e} onChange={x=>se(x.target.value)} required/></label><label>Password<input type="password" placeholder="Enter password" value={p} onChange={x=>sp(x.target.value)} required/></label>{m&&<div className="error">{m}</div>}<button className="primary" disabled={busy}>{busy?"Signing in…":"Sign In"}</button></form></div>
}

function App(){
 const[session,setSession]=useState(null),[me,setMe]=useState(null),[clients,setClients]=useState([]),[payments,setPayments]=useState([]),[tab,setTab]=useState("Dashboard"),[loading,setLoading]=useState(true),[err,setErr]=useState("");
 const load=async()=>{if(!sb)return;setLoading(true);setErr("");const{data:{user}}=await sb.auth.getUser();if(!user){setLoading(false);return}const[a,b,c]=await Promise.all([sb.from("profiles").select("*").eq("id",user.id).single(),sb.from("clients").select("*").order("created_at",{ascending:false}),sb.from("payments").select("*").order("payment_date",{ascending:false})]);if(a.error)setErr(a.error.message);if(b.error)setErr(b.error.message);if(c.error)setErr(c.error.message);setMe(a.data);setClients(b.data||[]);setPayments(c.data||[]);setLoading(false)};
 useEffect(()=>{if(!sb){setLoading(false);return}sb.auth.getSession().then(({data})=>setSession(data.session));const q=sb.auth.onAuthStateChange((_,s)=>setSession(s));return()=>q.data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 if(!session)return <Login/>;
 const total=clients.reduce((x,c)=>x+Number(c.final_amount||0),0),received=payments.reduce((x,p)=>x+Number(p.amount||0),0),due=Math.max(total-received,0);
 const nav=[{n:"Dashboard",i:"⌂"},{n:"Clients",i:"♙"},{n:"Payments",i:"▣"},{n:"Reports",i:"▥"}];
 return <div className="app"><aside><Brand/><nav>{nav.map(x=><button key={x.n} className={tab===x.n?"nav active":"nav"} onClick={()=>setTab(x.n)}><span>{x.i}</span>{x.n}</button>)}</nav><button className="signout" onClick={()=>sb.auth.signOut()}><span>↪</span>Sign Out</button></aside><main><header><div><div className="eyebrow">NP INTERIOR DESIGN</div><h1>{tab}</h1></div><div className="user"><div className="avatar">NP</div><div><strong>{me?.full_name||session.user.email}</strong><small>{me?.role||"User"}</small></div><span>⌄</span></div></header>{err&&<div className="errorBanner">{err}<button onClick={()=>setErr("")}>×</button></div>}{loading?<div className="loading">Loading your workspace…</div>:tab==="Dashboard"?<Dashboard total={total} received={received} due={due} clients={clients} payments={payments}/>:tab==="Clients"?<Clients clients={clients} reload={load}/>:tab==="Payments"?<Payments clients={clients} payments={payments} reload={load}/>:<Reports clients={clients} payments={payments}/>}</main></div>
}

function Dashboard({total,received,due,clients,payments}){
 const status=[{name:"Received",value:received},{name:"Balance",value:due}];const monthly={};payments.forEach(p=>{const k=p.payment_date?.slice(0,7)||"Unknown";monthly[k]=(monthly[k]||0)+Number(p.amount||0)});const md=Object.entries(monthly).sort().slice(-8).map(([month,amount])=>({month,amount}));
 return <div className="page"><div className="hero"><div><span className="eyebrow">OVERVIEW</span><h2>Good to see you, Nikunj.</h2><p>Keep your project collections and payment history under control.</p></div><div className="heroBadge">LIVE DATA<br/><b>SUPABASE</b></div></div><div className="cards"><Metric title="TOTAL PROJECT VALUE" value={money(total)} icon="◈"/><Metric title="PAYMENT RECEIVED" value={money(received)} icon="✓"/><Metric title="BALANCE DUE" value={money(due)} icon="₹"/><Metric title="PROJECTS" value={clients.length} icon="#"/></div><div className="chartGrid"><section className="panel chartPanel"><div className="panelHead"><div><span className="eyebrow">COLLECTION</span><h3>Payment Status</h3></div><span className="miniPill">{total?Math.round(received/total*100):0}% received</span></div><div className="donut"><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={status} dataKey="value" innerRadius={72} outerRadius={100} paddingAngle={3}>{status.map((_,i)=><Cell key={i} fill={i===0?"#15191d":"#cfd3d6"}/>)}</Pie><Tooltip formatter={v=>money(v)}/></PieChart></ResponsiveContainer><div className="donutCenter"><strong>{total?Math.round(received/total*100):0}%</strong><span>received</span></div></div></section><section className="panel chartPanel"><div className="panelHead"><div><span className="eyebrow">MONTHLY</span><h3>Collection Trend</h3></div></div><ResponsiveContainer width="100%" height={280}><BarChart data={md} margin={{top:15,right:10,left:0,bottom:5}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} tickFormatter={v=>v>=1000?`₹${Math.round(v/1000)}k`:v}/><Tooltip formatter={v=>money(v)}/><Bar dataKey="amount" fill="#15191d" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></section></div></div>
}
function Metric({title,value,icon}){return <div className="metric"><div className="metricIcon">{icon}</div><small>{title}</small><strong>{value}</strong><span className="metricLine"/></div>}

function Clients({clients,reload}){
 const empty={client_name:"",project_name:"",project_type:"Interior Design",final_amount:""};const[f,setF]=useState(empty);const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setMsg("");if(!f.client_name.trim()||!f.project_name.trim()||Number(f.final_amount)<=0){setMsg("Please enter client name, project name and a valid final amount.");return}setBusy(true);const{error}=await sb.from("clients").insert({client_name:f.client_name.trim(),project_name:f.project_name.trim(),project_type:f.project_type,final_amount:Number(f.final_amount)});if(error)setMsg(error.message);else{setF(empty);setMsg("Client added successfully.");await reload()}setBusy(false)};
 return <div className="page"><div className="sectionIntro"><div><span className="eyebrow">PROJECTS</span><h2>Clients</h2><p>Keep every project and final amount organized.</p></div><span className="countPill">{clients.length} projects</span></div><section className="panel"><div className="panelTitle"><span className="roundIcon">+</span><div><h3>Add Client</h3><p>Start a new project record.</p></div></div><form className="smartForm" onSubmit={submit}><Field label="Client Name" value={f.client_name} onChange={v=>setF({...f,client_name:v})} required/><Field label="Project Name" value={f.project_name} onChange={v=>setF({...f,project_name:v})} required/><Field label="Project Type" value={f.project_type} onChange={v=>setF({...f,project_type:v})}/><Field label="Final Amount" type="number" value={f.final_amount} onChange={v=>setF({...f,final_amount:v})} required/><button className="primary formButton" disabled={busy}>{busy?"Saving…":"Add Client"}</button></form>{msg&&<div className={msg.includes("successfully")?"success":"error"}>{msg}</div>}</section><DataTable columns={["Client Name","Project Name","Project Type","Final Amount","Action"]} rows={clients.map(c=>[c.client_name,c.project_name,c.project_type,money(c.final_amount),<button className="deleteBtn" title="Delete client" onClick={async()=>{if(!window.confirm(`Delete client ${c.client_name}? This may fail if payments are linked.`))return;const{error}=await sb.from("clients").delete().eq("id",c.id);if(error)setMsg(`Client could not be deleted: ${error.message}`);else{setMsg("Client deleted successfully.");await reload()}}}>Delete</button>])} empty="No clients yet. Add your first project above."/></div>
}

function Payments({clients,payments,reload}){
 const empty={client_id:"",payment_date:dateNow(),amount:"",payment_mode:"upi",reference_no:"",notes:""};const[f,setF]=useState(empty);const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);const[search,setSearch]=useState("");
 const submit=async e=>{e.preventDefault();setMsg("");if(!f.client_id){setMsg("Please select a client.");return}if(Number(f.amount)<=0){setMsg("Please enter a valid payment amount.");return}setBusy(true);const{data:{user}}=await sb.auth.getUser();const base={client_id:f.client_id,payment_date:f.payment_date,amount:Number(f.amount),payment_mode:f.payment_mode,reference_no:f.reference_no.trim()||null,notes:f.notes.trim()||null};let error=null;let result=await sb.from("payments").insert({...base,created_by:user?.id}).select().single();error=result.error;
 if(error&&/created_by|column/i.test(error.message||"")&&/does not exist|not found|could not find/i.test(error.message||"")){result=await sb.from("payments").insert(base).select().single();error=result.error}
 if(error){setMsg(`Payment could not be saved: ${error.message}`)}else{setF(empty);setMsg("Payment added successfully.");await reload()}setBusy(false)};
 const filtered=payments.filter(p=>{const c=clients.find(x=>x.id===p.client_id);const s=search.toLowerCase();return !s||[c?.client_name,p.payment_mode,p.reference_no,p.notes].some(x=>String(x||"").toLowerCase().includes(s))});
 return <div className="page"><div className="sectionIntro"><div><span className="eyebrow">COLLECTIONS</span><h2>Payments</h2><p>Record and track client payments.</p></div></div><section className="panel"><div className="panelTitle"><span className="roundIcon">+</span><div><h3>Add Payment</h3><p>Save a payment against a client.</p></div></div><form className="smartForm paymentForm" onSubmit={submit}><label>Client *<select value={f.client_id} onChange={e=>setF({...f,client_id:e.target.value})} required><option value="">Select Client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.client_name}</option>)}</select></label><Field label="Payment Date *" type="date" value={f.payment_date} onChange={v=>setF({...f,payment_date:v})}/><Field label="Amount *" type="number" value={f.amount} onChange={v=>setF({...f,amount:v})} placeholder="₹ 0" required/><label>Payment Mode *<select value={f.payment_mode} onChange={e=>setF({...f,payment_mode:e.target.value})}><option value="upi">UPI</option><option value="bank_transfer">Bank Transfer</option><option value="cash">Cash</option><option value="cheque">Cheque</option><option value="card">Card</option><option value="other">Other</option></select></label><Field label="Reference No." value={f.reference_no} onChange={v=>setF({...f,reference_no:v})} placeholder="UPI / UTR / Cheque No."/><Field label="Notes (Optional)" value={f.notes} onChange={v=>setF({...f,notes:v})} placeholder="Advance, milestone, final payment…"/><button className="primary formButton" disabled={busy}>{busy?"Saving…":"Add Payment"}</button></form>{msg&&<div className={msg.includes("successfully")?"success":"error"}>{msg}</div>}</section><section className="panel"><div className="historyHead"><div className="panelTitle"><span className="roundIcon">▣</span><div><h3>Payment History</h3><p>{filtered.length} payment records</p></div></div><input className="search" placeholder="Search payment…" value={search} onChange={e=>setSearch(e.target.value)}/></div><DataTable columns={["No.","Payment Date","Client Name","Payment Mode","Reference No.","Amount","Notes","Action"]} rows={filtered.map((p,i)=>[i+1,p.payment_date,clients.find(c=>c.id===p.client_id)?.client_name||"—",p.payment_mode?.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase()),p.reference_no||"—",money(p.amount),p.notes||"—",<button className="deleteBtn" title="Delete payment" onClick={async()=>{if(!window.confirm(`Delete this payment of ${money(p.amount)}?`))return;const{error}=await sb.from("payments").delete().eq("id",p.id);if(error)setMsg(`Payment could not be deleted: ${error.message}`);else{setMsg("Payment deleted successfully.");await reload()}}}>Delete</button>])} empty="No payments yet. Add the first payment above."/><div className="totalBar"><span>Total Received</span><strong>{money(payments.reduce((a,p)=>a+Number(p.amount||0),0))}</strong></div></section></div>
}

function Field({label,value,onChange,type="text",placeholder}){return <label>{label}{type==="number"?<input type={type} min="0" step="1" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder||"Enter amount"}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</label>}
function DataTable({columns,rows,empty}){return <div className="tableWrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>):<tr><td className="empty" colSpan={columns.length}>{empty}</td></tr>}</tbody></table></div>}

function Reports({clients,payments}){const[id,setId]=useState("");const c=clients.find(x=>x.id===id);const ps=payments.filter(x=>x.client_id===id);const received=ps.reduce((a,x)=>a+Number(x.amount||0),0);const pdf=()=>{if(!c)return;const d=new jsPDF();d.setDrawColor(220);d.line(20,32,190,32);d.setFontSize(19);d.text("NP INTERIOR DESIGN",20,22);d.setFontSize(9);d.text("PAYMENT STATEMENT",150,22);d.setFontSize(11);d.text(`Client: ${c.client_name}`,20,45);d.text(`Project: ${c.project_name}`,20,53);d.text(`Project Type: ${c.project_type||"—"}`,20,61);let y=78;d.setFontSize(9);d.text("DATE",20,y);d.text("MODE",65,y);d.text("REFERENCE",105,y);d.text("AMOUNT",165,y);ps.forEach(p=>{y+=8;if(y>270){d.addPage();y=20}d.text(p.payment_date||"—",20,y);d.text(p.payment_mode||"—",65,y);d.text(p.reference_no||"—",105,y);d.text(money(p.amount),165,y)});y+=16;d.text(`Final Amount: ${money(c.final_amount)}`,120,y);d.text(`Total Received: ${money(received)}`,120,y+8);d.text(`Balance Due: ${money(Number(c.final_amount)-received)}`,120,y+16);d.text("Thank you for your trust and association.",20,y+35);d.save(`NP_INTERIOR_DESIGN_${c.client_name.replace(/[^a-z0-9]+/gi,"_")}_PAYMENT_STATEMENT.pdf`)};return <div className="page"><div className="sectionIntro"><div><span className="eyebrow">DOCUMENTS</span><h2>Reports</h2><p>Generate a clean A4 payment statement for any client.</p></div></div><section className="panel reportCard"><span className="roundIcon">▤</span><h3>A4 Payment Statement</h3><p>Includes project details, complete payment history, total received and balance due.</p><select value={id} onChange={e=>setId(e.target.value)}><option value="">Select Client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.client_name} — {c.project_name}</option>)}</select><button className="primary" disabled={!id} onClick={pdf}>Generate PDF</button>{c&&<div className="reportPreview"><div><span>FINAL AMOUNT</span><strong>{money(c.final_amount)}</strong></div><div><span>RECEIVED</span><strong>{money(received)}</strong></div><div><span>BALANCE</span><strong>{money(Number(c.final_amount)-received)}</strong></div></div>}</section></div>}

createRoot(document.getElementById("root")).render(<App/>);
